name: Deploy to AWS Amplify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to AWS Amplify
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build application
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
        run: npm run build
        
      # Using the pre-installed AWS CLI in GitHub Actions runner
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      # Verify the pre-installed AWS CLI version
      - name: Verify AWS CLI
        run: aws --version
          
      - name: Deploy to AWS Amplify
        run: |
          echo "Starting deployment to AWS Amplify..."
          # Create a deployment ZIP file
          zip -r build.zip build/
          
          # Start the deployment job using pre-installed AWS CLI
          aws amplify start-deployment \
            --app-id ${{ secrets.AMPLIFY_APP_ID }} \
            --branch-name production \
            --source-url file://$(pwd)/build.zip
          
          echo "Deployment initiated successfully"
        # AWS credentials are already configured by the aws-actions/configure-aws-credentials step
